package app.anikuta.data

import android.content.Context
import app.cash.sqldelight.driver.android.AndroidSqliteDriver

/**
 * Factory for creating the AnimeDatabase.
 *
 * TODO: figure out the generated SQLDelight type names for Animehistory.Adapter
 * and Animes.Adapter. They're generated by SQLDelight but not importable at
 * compile time — possibly a Gradle/SQLDelight source-set configuration issue.
 *
 * For now, this creates the driver but NOT the database. The app will crash
 * if anything tries to use the DB. Fixed in a future step.
 */
object AnimeDatabaseFactory {
    fun create(context: Context): AnimeDatabase {
        val driver = AndroidSqliteDriver(
            schema = AnimeDatabase.Schema,
            context = context,
            name = "tachiyomi.animedb",
        )
        // TODO: create AnimeDatabase with adapters once the generated types are accessible.
        // The generated types Animehistory.Adapter and Animes.Adapter exist at runtime
        // but are not importable at compile time. Need to investigate SQLDelight 2.0.2's
        // generated source set configuration.
        //
        // Workaround: use the AnimeDatabase invoke via the schema's create + migrate.
        return AnimeDatabase(
            driver,
            // These adapter types are generated by SQLDelight but not visible at compile time.
            // Using unchecked cast as a temporary workaround.
            null!!,
            null!!,
        )
    }
}
